name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx =myst_parser
      - name: Sphinx build
        run: |
          sphinx-build . _build
#         sphinx-build doc _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
          
# name: "Pull Request Docs Check"
# on: 
#   push:
#     branches:
#       - main
      
# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: ammaraskar/sphinx-action@master
#       with:
#         docs-folder: "./"
        
# name: Sphinx Build

# on:
#   push:
#     branches: [ "main" ]

# permissions:
#   contents: read
  
# # You may pin to the exact commit or the version.
# # uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Sphinx Build
#         uses: ammaraskar/sphinx-action@0.4
#         with:
#           # The folder containing your sphinx docs.
#           docs-folder: . # default is docs/
#           # The command used to build your documentation.
#           # build-command: # optional, default is make html
#           # Run before the build command, you can use this to install system level dependencies, for example with "apt-get update -y && apt-get install -y perl"
#           # pre-build-command: # optional
          